/* Automatically generated by './packages/index.ts' */
import BtnList from './btn-list/index'

const components = [
  BtnList
];

const install = function(Vue: typeof import("vue/types/umd")) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
 BtnList
}
